import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { zipSync, strToU8 } from 'fflate';
import { parseXlsx, readSheetNames } from '../src/data/xlsx.js';
import { readXlsxRecords } from '../src/data/records.js';
import { DoclystError } from '../src/errors.js';
import { FIXED_ARCHIVE_TIMESTAMP } from '../src/internal/deterministic.js';
import { buildXlsx, row, numberCell, sharedCell, DATE_STYLES } from './helpers/xlsx.js';

/**
 * `staff.xlsx` is generated by openpyxl (see fixtures/generate.py), so the
 * parser is checked against a real writer's output rather than against our own
 * encoder. Its contents are entirely synthetic.
 */
const STAFF_XLSX = new Uint8Array(
  readFileSync(fileURLToPath(new URL('./fixtures/staff.xlsx', import.meta.url))),
);

describe('a workbook written by a real producer', () => {
  it('lists the worksheets in tab order', () => {
    expect(readSheetNames(STAFF_XLSX)).toEqual(['Staff', 'Archive']);
  });

  it('reads the header row', () => {
    expect(parseXlsx(STAFF_XLSX)[0]).toEqual([
      'Full Name', 'Basic Salary', 'Start Date', 'Staff ID', 'Confirmed', 'Notes',
    ]);
  });

  it('resolves shared strings', () => {
    expect(parseXlsx(STAFF_XLSX)[1]?.[0]).toBe('Aisha Rahman');
  });

  it('renders a date-formatted number as a calendar date, not a serial', () => {
    // Excel stores dates as plain numbers; only the cell format distinguishes
    // them, so without style handling this column reads as "46037".
    expect(parseXlsx(STAFF_XLSX)[1]?.[2]).toBe('2026-01-15');
  });

  it('includes the time only when the value carries one', () => {
    expect(parseXlsx(STAFF_XLSX)[4]?.[2]).toBe('2026-03-01 09:30:00');
  });

  it('preserves a decimal without re-rendering it through floating point', () => {
    expect(parseXlsx(STAFF_XLSX)[2]?.[1]).toBe('5200.5');
  });

  it('reads booleans', () => {
    expect(parseXlsx(STAFF_XLSX)[1]?.[4]).toBe('TRUE');
    expect(parseXlsx(STAFF_XLSX)[2]?.[4]).toBe('FALSE');
  });

  it('preserves non-ASCII text', () => {
    expect(parseXlsx(STAFF_XLSX)[4]?.[0]).toBe('Zoë Müller');
  });

  it('keeps a sparse row aligned with its headers', () => {
    // Excel omits empty cells entirely, so alignment depends on reading each
    // cell's reference rather than counting positions.
    const record = readXlsxRecords(STAFF_XLSX).records[4]!;
    expect(record['Full Name']).toBe('Sparse Row');
    expect(record['Staff ID']).toBe('EMP-0005');
    expect(record['Basic Salary']).toBe('');
  });

  it('produces records keyed by header', () => {
    const { fields, records } = readXlsxRecords(STAFF_XLSX);
    expect(fields[0]).toBe('Full Name');
    expect(records).toHaveLength(5);
    expect(records[0]?.['Basic Salary']).toBe('4500');
  });

  describe('sheet selection', () => {
    it('defaults to the first sheet', () => {
      expect(readXlsxRecords(STAFF_XLSX).records[0]?.['Full Name']).toBe('Aisha Rahman');
    });

    it('selects a sheet by name', () => {
      const { records } = readXlsxRecords(STAFF_XLSX, { sheet: 'Archive' });
      expect(records).toEqual([{ 'Full Name': 'Former Person', 'Staff ID': 'EMP-9999' }]);
    });

    it('selects a sheet by index', () => {
      expect(readXlsxRecords(STAFF_XLSX, { sheet: 1 }).records[0]?.['Staff ID']).toBe('EMP-9999');
    });

    it('lists the available sheets when the name is wrong', () => {
      // Sheet names are structural labels, so naming them helps without
      // disclosing anything about the records.
      expect(() => readXlsxRecords(STAFF_XLSX, { sheet: 'Payroll' })).toThrow(/Available: Staff, Archive/);
    });

    it('rejects an out-of-range index', () => {
      expect(() => readXlsxRecords(STAFF_XLSX, { sheet: 9 })).toThrow(/does not exist/);
    });
  });
});

describe('cell types a normal writer will not emit', () => {
  it('reads a formula"s cached result without evaluating the formula', () => {
    // Doclyst never evaluates a formula; it reads what the spreadsheet last
    // computed, which is what the operator saw on screen.
    const xlsx = buildXlsx({
      sheetData:
        row(1, `<c r="A1" t="str"><v>Total</v></c>`) +
        row(2, `<c r="A2" t="str"><f>CONCATENATE("a","b")</f><v>ab</v></c>`),
    });
    expect(parseXlsx(xlsx)[1]?.[0]).toBe('ab');
  });

  it('treats a formula with no cached result as empty', () => {
    // Some writers store the formula but never its result. The neighbouring
    // cell keeps the row from being trimmed as trailing blank formatting.
    const xlsx = buildXlsx({
      sheetData:
        row(1, `<c r="A1" t="str"><v>H</v></c><c r="B1" t="str"><v>H2</v></c>`) +
        row(2, `<c r="A2"><f>1+1</f></c><c r="B2" t="str"><v>present</v></c>`),
    });
    expect(parseXlsx(xlsx)[1]).toEqual(['', 'present']);
  });

  it('reads inline strings', () => {
    const xlsx = buildXlsx({
      sheetData: row(1, `<c r="A1" t="inlineStr"><is><t>Inline Header</t></is></c>`),
    });
    expect(parseXlsx(xlsx)[0]?.[0]).toBe('Inline Header');
  });

  it('joins rich-text runs into one value', () => {
    // Part-bold text is stored as several runs; taking the first would
    // silently truncate the value.
    const xlsx = buildXlsx({
      sheetData: row(1, `<c r="A1" t="inlineStr"><is><r><t>Bold</t></r><r><t> and plain</t></r></is></c>`),
    });
    expect(parseXlsx(xlsx)[0]?.[0]).toBe('Bold and plain');
  });

  it('excludes phonetic guide text from the value', () => {
    const xlsx = buildXlsx({
      sheetData: row(1, `<c r="A1" t="inlineStr"><is><t>Tokyo</t><rPh sb="0" eb="2"><t>ignored</t></rPh></is></c>`),
    });
    expect(parseXlsx(xlsx)[0]?.[0]).toBe('Tokyo');
  });

  it('passes an error cell through so it is visible rather than blank', () => {
    const xlsx = buildXlsx({
      sheetData: row(1, `<c r="A1" t="str"><v>H</v></c>`) + row(2, `<c r="A2" t="e"><v>#REF!</v></c>`),
    });
    expect(parseXlsx(xlsx)[1]?.[0]).toBe('#REF!');
  });

  it('decodes XML entities in cell text', () => {
    const xlsx = buildXlsx({
      sheetData: row(1, `<c r="A1" t="s"><v>0</v></c>`),
      sharedStrings: ['Tan &amp; Lim &lt;Pte&gt;'],
    });
    expect(parseXlsx(xlsx)[0]?.[0]).toBe('Tan & Lim <Pte>');
  });
});

describe('date conversion', () => {
  const dated = (serial: string, epoch1904 = false) =>
    parseXlsx(
      buildXlsx({
        sheetData: row(1, numberCell('A1', serial, 1)),
        styles: DATE_STYLES,
        epoch1904,
      }),
    )[0]?.[0];

  it('converts a 1900-system serial', () => {
    expect(dated('46037')).toBe('2026-01-15');
  });

  it('accounts for the fictional 29 February 1900', () => {
    // Excel deliberately contains a leap day that never existed, kept for
    // Lotus 1-2-3 compatibility, so early serials need correcting.
    expect(dated('1')).toBe('1900-01-01');
    expect(dated('59')).toBe('1900-02-28');
    expect(dated('61')).toBe('1900-03-01');
  });

  it('converts a 1904-system serial', () => {
    expect(dated('0', true)).toBe('1904-01-01');
  });

  it('leaves an unstyled number as a number', () => {
    const xlsx = buildXlsx({ sheetData: row(1, numberCell('A1', '46037')) });
    expect(parseXlsx(xlsx)[0]?.[0]).toBe('46037');
  });

  it('does not mistake a currency format for a date', () => {
    // The `d` inside a quoted literal must not make this a date column.
    const xlsx = buildXlsx({
      sheetData: row(1, numberCell('A1', '4500', 1)),
      styles: `<numFmts><numFmt numFmtId="164" formatCode="&quot;Paid&quot;#,##0"/></numFmts>
<cellXfs count="2"><xf numFmtId="0"/><xf numFmtId="164"/></cellXfs>`,
    });
    expect(parseXlsx(xlsx)[0]?.[0]).toBe('4500');
  });

  it('recognises built-in date formats', () => {
    const xlsx = buildXlsx({
      sheetData: row(1, numberCell('A1', '46037', 1)),
      styles: `<cellXfs count="2"><xf numFmtId="0"/><xf numFmtId="14"/></cellXfs>`,
    });
    expect(parseXlsx(xlsx)[0]?.[0]).toBe('2026-01-15');
  });
});

describe('column alignment', () => {
  it('maps cell references beyond Z', () => {
    const xlsx = buildXlsx({ sheetData: row(1, numberCell('AA1', '27')) });
    const first = parseXlsx(xlsx)[0]!;
    expect(first).toHaveLength(27);
    expect(first[26]).toBe('27');
  });

  it('falls back to position when a cell has no reference', () => {
    const xlsx = buildXlsx({ sheetData: row(1, `<c><v>1</v></c><c><v>2</v></c>`) });
    expect(parseXlsx(xlsx)[0]).toEqual(['1', '2']);
  });

  it('drops trailing rows that hold only formatting', () => {
    const xlsx = buildXlsx({
      sheetData: row(1, numberCell('A1', '1')) + row(2, `<c r="A2" s="1"/>`),
    });
    expect(parseXlsx(xlsx)).toHaveLength(1);
  });
});

describe('rejected input', () => {
  it('rejects a file that is not a ZIP', () => {
    expect(() => parseXlsx(new Uint8Array([1, 2, 3, 4]))).toThrow(/not a valid XLSX/);
  });

  it('rejects an empty input', () => {
    expect(() => parseXlsx(new Uint8Array())).toThrow(DoclystError);
  });

  it('rejects a ZIP that is not a workbook', () => {
    const notXlsx = zipSync({ 'hello.txt': strToU8('hi') }, { mtime: FIXED_ARCHIVE_TIMESTAMP });
    expect(() => parseXlsx(notXlsx)).toThrow(/xl\/workbook\.xml is missing/);
  });

  it('rejects a relationship target that escapes the archive', () => {
    // A crafted workbook must not be able to point at a part outside the zip.
    expect(() =>
      parseXlsx(buildXlsx({ sheetData: '', sheetTarget: '../../../etc/passwd' })),
    ).toThrow(/outside the archive/);
  });

  it('does not echo document bytes when a workbook is corrupt', () => {
    const corrupt = new Uint8Array([0x50, 0x4b, 0x03, 0x04, ...new Array(40).fill(0xff)]);
    try {
      parseXlsx(corrupt);
      expect.unreachable();
    } catch (error) {
      expect((error as DoclystError).message).toMatch(/details withheld|not a valid XLSX/);
    }
  });

  it('enforces the column limit', () => {
    const xlsx = buildXlsx({ sheetData: row(1, numberCell('ZZ1', '1')) });
    expect(() => parseXlsx(xlsx, { maxColumns: 10 })).toThrow(/exceeds the supported limit/);
  });

  it('enforces the row limit', () => {
    const rows = Array.from({ length: 30 }, (_, i) => row(i + 1, numberCell(`A${i + 1}`, '1'))).join('');
    expect(() => parseXlsx(buildXlsx({ sheetData: rows }), { maxRows: 5 })).toThrow(/exceeds the supported limit/);
  });

  it('rejects a workbook with no worksheets', () => {
    const empty = zipSync(
      {
        'xl/workbook.xml': strToU8('<?xml version="1.0"?><workbook><sheets/></workbook>'),
      },
      { mtime: FIXED_ARCHIVE_TIMESTAMP },
    );
    expect(() => parseXlsx(empty)).toThrow(/no worksheets/);
  });
});

describe('formula injection from a workbook', () => {
  it('carries a formula-looking value through as inert text', () => {
    // Doclyst never evaluates it. The guard that matters is on output: this
    // value is neutralised if it is ever written into a CSV manifest.
    const xlsx = buildXlsx({
      sheetData: row(1, sharedCell('A1', 0)),
      sharedStrings: ['=HYPERLINK("http://example.test","click")'],
    });
    expect(parseXlsx(xlsx)[0]?.[0]).toBe('=HYPERLINK("http://example.test","click")');
  });
});
