import { zipSync, strToU8 } from 'fflate';
import { FIXED_ARCHIVE_TIMESTAMP } from '../../src/internal/deterministic.js';

/**
 * Hand-built XLSX parts, for cases a normal writer cannot produce.
 *
 * The committed `fixtures/staff.xlsx` is generated by openpyxl and covers the
 * realistic path. These helpers cover what openpyxl will not emit — cached
 * formula results, inline strings, error cells, the 1904 epoch — and hostile
 * shapes such as a relationship target pointing outside the archive.
 */

export interface BuildXlsxOptions {
  /** Contents of `<sheetData>` for the first worksheet. */
  readonly sheetData: string;
  readonly sharedStrings?: readonly string[];
  /** Raw `<styles.xml>` content; omit for a workbook with no styles. */
  readonly styles?: string;
  /** Use the 1904 date system. */
  readonly epoch1904?: boolean;
  /** Override the relationship target for the first sheet. */
  readonly sheetTarget?: string;
  /** Extra or replacement archive entries. */
  readonly extraParts?: Readonly<Record<string, string>>;
}

export function buildXlsx(options: BuildXlsxOptions): Uint8Array {
  const target = options.sheetTarget ?? 'worksheets/sheet1.xml';

  const workbook = `<?xml version="1.0" encoding="UTF-8"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
${options.epoch1904 ? '<workbookPr date1904="1"/>' : ''}
<sheets><sheet name="Sheet1" sheetId="1" r:id="rId1"/></sheets></workbook>`;

  const rels = `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="${target}"/>
</Relationships>`;

  const sheet = `<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<sheetData>${options.sheetData}</sheetData></worksheet>`;

  const parts: Record<string, Uint8Array> = {
    '[Content_Types].xml': strToU8('<?xml version="1.0"?><Types/>'),
    'xl/workbook.xml': strToU8(workbook),
    'xl/_rels/workbook.xml.rels': strToU8(rels),
    'xl/worksheets/sheet1.xml': strToU8(sheet),
  };

  if (options.sharedStrings) {
    const items = options.sharedStrings.map((s) => `<si><t>${s}</t></si>`).join('');
    parts['xl/sharedStrings.xml'] = strToU8(
      `<?xml version="1.0"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">${items}</sst>`,
    );
  }
  if (options.styles) {
    parts['xl/styles.xml'] = strToU8(`<?xml version="1.0"?><styleSheet>${options.styles}</styleSheet>`);
  }
  for (const [name, content] of Object.entries(options.extraParts ?? {})) {
    parts[name] = strToU8(content);
  }

  return zipSync(parts, { mtime: FIXED_ARCHIVE_TIMESTAMP });
}

/** A `<row>` containing the given cell XML. */
export function row(index: number, cells: string): string {
  return `<row r="${index}">${cells}</row>`;
}

/** A cell holding a literal number, optionally with a style index. */
export function numberCell(ref: string, value: string, style?: number): string {
  return `<c r="${ref}"${style === undefined ? '' : ` s="${style}"`}><v>${value}</v></c>`;
}

/** A cell referencing the shared string table. */
export function sharedCell(ref: string, index: number): string {
  return `<c r="${ref}" t="s"><v>${index}</v></c>`;
}

/** Styles declaring one date format at cell-format index 1. */
export const DATE_STYLES = `<numFmts><numFmt numFmtId="164" formatCode="dd/mm/yyyy"/></numFmts>
<cellXfs count="2"><xf numFmtId="0"/><xf numFmtId="164"/></cellXfs>`;
